version: "3"

services:
  app:
    build: ./
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: YOUR_DOMAIN
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: YOUR_DOMAIN
      LETSENCRYPT_EMAIL: YOUR_EMAIL
networks:
  default:
    external:
      name: nginx-proxy