version: '3.7'

services:

  docker10000-prod:
    container_name: docker10000
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: kenguru_production_nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
